# Autogenerated by devscripts/update-version.py

__version__ = '2026.09.20'

RELEASE_GIT_HEAD = 'c33c1c66648f50effafd19c809a9a2ebd2bc5708'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'ridhozahrann/omniFetch'

_pkg_version = '2026.09.20'
